data:
    corpus_1:
        path_src: /RPSubAlign/SMILES representation/data/UPSTO-50k/RPSubAlign_1x/src-train.txt
        path_tgt: /RPSubAlign/SMILES representation/data/UPSTO-50k/RPSubAlign_1x/tgt-train.txt
    valid:
        path_src: /RPSubAlign/SMILES representation/data/UPSTO-50k/RPSubAlign_1x/src-val_a1.txt
        path_tgt: /RPSubAlign/SMILES representation/UPSTO-50k/RPSubAlign_1x/tgt-val_a1.txt
src_vocab: /RPSubAlign/SMILES representation/data/USPTO-50K/RPSubAlign/vocab.src
tgt_vocab: /RPSubAlign/SMILES representation/data/USPTO-50K/RPSubAlign/vocab.src
#### Filter
src_seq_length: 500
tgt_seq_length: 500
n_sample: 0
save_model: /RPSubAlign/SMILES representation/model/RPSubAlign_1x/RPSubAlign_1x
tensorboard_log_dir: /RPSubAlign/SMILES representation/log/tensorboard/RPSubAlign_1x
tensorboard: True


keep_checkpoint: 10
seed: 3435
train_steps: 70000
valid_steps: 5000
warmup_steps: 8000
report_every: 100

decoder_type: transformer
encoder_type: transformer
word_vec_size: 256
rnn_size: 256
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 1
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 1.0
max_grad_norm: 0.0

batch_size: 128
valid_batch_size: 128
batch_type: sents
normalization: sents
dropout: 0.3
attention_dropout: 0.3
label_smoothing: 0.0

max_generator_batches: 0

param_init: 0.0
param_init_glorot: 'true'
position_encoding: 'true'

world_size: 1
gpu_ranks: 
 - 0
